#设置内嵌端口号
server:
  port: 8080
  servlet:
    context-path: /

#配置dubbo
dubbo:
  application:
    name: dubbo-consumer
  registry:
    protocol: zookeeper
    address: 192.168.217.129:2181
  scan:
    base-packages: com.xihai.controller
